### ISSUE TITLE
AchillesResourceBuilder often fails to start an embedded cassandra

### ISSUE THREAD

**Issue by bric3** [doanduyhai/Achilles#131]
This usually happen in maven when a cassandra-unit instance is started **before** achilles resource, e.g. in a previous test.

Then Achilles cannot connect to the required instance and fails with this stack trace.

```
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9330 (com.datastax.driver.core.TransportException: [localhost/127.0.0.1:9330] Cannot connect))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:195)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:79)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1143)
	at com.datastax.driver.core.Cluster.init(Cluster.java:149)
	at com.datastax.driver.core.Cluster.connect(Cluster.java:225)
	at com.datastax.driver.core.Cluster.connect(Cluster.java:258)
	at info.archinnov.achilles.embedded.AchillesInitializer.createKeyspaceIfNeeded(AchillesInitializer.java:139)
	at info.archinnov.achilles.embedded.AchillesInitializer.initialize(AchillesInitializer.java:91)
	at info.archinnov.achilles.embedded.AchillesInitializer.initializeFromParameters(AchillesInitializer.java:61)
	at info.archinnov.achilles.embedded.CassandraEmbeddedServer.<init>(CassandraEmbeddedServer.java:69)
	at info.archinnov.achilles.junit.AchillesResource.initResource(AchillesResource.java:60)
	at info.archinnov.achilles.junit.AchillesResource.<init>(AchillesResource.java:51)
	at info.archinnov.achilles.junit.AchillesResourceBuilder.build(AchillesResourceBuilder.java:105)
	at my.company.MyTest.<init>(MyTest.java:48)
```

After a brief investigation I discovered that `ServerStarter#isAlreadyRunning` is using an MBean to discover if a cluster exists 

```java
        MBeanServer mbs = ManagementFactory.getPlatformMBeanServer();
        try {
            MBeanInfo mBeanInfo = mbs.getMBeanInfo(new ObjectName("org.apache.cassandra.db:type=StorageService"));
            if (mBeanInfo != null) {
                return true;
            }
            return false;
        } catch (InstanceNotFoundException e) {
```

However what happens is that the cassandra daemon launched by cassandra-unit uses other settings and especially other ports.

What I propose is to use instead other properties in the MBean like the `ClusterName` attribute, which is by default `Test Cluster`, see [doc](http://www.datastax.com/documentation/cassandra/2.0/cassandra/configuration/configCassandra_yaml_r.html) on how ta change it via the cluster_name` property.

Then the check could be changed to something like 

```java
String actualClusterName= ManagementFactory.getPlatformMBeanServer()
    .getAttribute(new ObjectName("org.apache.cassandra.db:type=StorageService"), "ClusterName");

return wantedClusterName.equals(actualClusterName);
````

Also the YAML config file should be placed in a temp directory / temp file, otherwise it may break tests when they are run concurrently, e.g. with `mvn test -T4`

**Comment by doanduyhai** [comment]
Closing this issue since it is using an old version of Achilles. Feel free to re-open it if facing the same issue with the new Achilles 4.1.x version
