### ISSUE TITLE
CqlColumn is not mapped to the java field

### ISSUE THREAD

**Issue by mdamak** [doanduyhai/Achilles#191]
In my Entity I have a field 

````java
@Colum
Counter totalForDay;
````

When I try to get the value of this counter by  `myEntity.getTotalForDay().get()` , I get a `NullPointerException`. 

This is the stacktrace
````java
java.lang.NullPointerException
	at info.archinnov.achilles.internal.statement.prepared.PreparedStatementBinder.bindForClusteredCounterSelect(PreparedStatementBinder.java:263)
	at info.archinnov.achilles.internal.context.DaoContext.getClusteredCounterColumn(DaoContext.java:230)
	at info.archinnov.achilles.internal.context.PersistenceContext$EntityFacade.getClusteredCounterColumn(PersistenceContext.java:509)
	at info.archinnov.achilles.internal.persistence.operations.CounterLoader.loadClusteredCounterColumn(CounterLoader.java:62)
	at info.archinnov.achilles.internal.proxy.ProxyInterceptor.interceptGetter(ProxyInterceptor.java:92)
	at info.archinnov.achilles.internal.proxy.ProxyInterceptor.intercept(ProxyInterceptor.java:75)
	at com.spideo.analytics.model.TotalUsers$$EnhancerByCGLIB$$9599987f.getTotalForDay(<generated>)
	at com.spideo.analytics.service.TotalUsersService.analyseLog(TotalUsersService.java:56)
	at com.spideo.analytics.service.TotalUsersServiceTest.findOne(TotalUsersServiceTest.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
````

So I added a name to my column I thought it is problem related to the fact that CQL is Case-insensitive.
````java
@Column(name="total_for_day")
public Counter totalForDay;`
````

But I had the same exception.

**Comment by ElPicador** [comment]
Thanks !
