### ISSUE TITLE
Achilles does not support static field only in rows

### ISSUE THREAD

**Issue by n0rad** [doanduyhai/Achilles#214]
if you insert a static field only you will not have clustering column.

when you will read this row, Achilles will do a validation from what is coming from the DB and will fail.

```
13:57:24.867 [6023616-23] ERROR .r.m.PrivateMessageApiErrorExceptionMapper:65 - Technical exception : info.archinnov.achilles.exception.AchillesException: Error, the component 'thread_id' from @CompoundPrimaryKey class 'class com.me.entity.LatestFullEntity$LatestFullKey' is null in Cassandra
	at info.archinnov.achilles.internal.validation.Validator.validateNotNull(Validator.java:43)
	at info.archinnov.achilles.internal.metadata.holder.PropertyMetaRowExtractor.validateExtractedCompoundPrimaryComponents(PropertyMetaRowExtractor.java:101)
	at info.archinnov.achilles.internal.metadata.holder.PropertyMetaRowExtractor.extractCompoundPrimaryKeyFromRow(PropertyMetaRowExtractor.java:89)
	at info.archinnov.achilles.internal.persistence.operations.EntityMapper.setPropertyToEntity(EntityMapper.java:51)
	at info.archinnov.achilles.internal.persistence.operations.EntityMapper.setNonCounterPropertiesToEntity(EntityMapper.java:42)
	at info.archinnov.achilles.internal.persistence.operations.SliceQueryExecutor$2.apply(SliceQueryExecutor.java:105)
	at info.archinnov.achilles.internal.persistence.operations.SliceQueryExecutor$2.apply(SliceQueryExecutor.java:99)
	at com.google.common.util.concurrent.Futures$1.apply(Futures.java:715)
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:863)
	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture$1.run(Futures.java:875)
	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
	at com.google.common.util.concurrent.Futures$ImmediateFuture.addListener(Futures.java:104)
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:871)
	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture$1.run(Futures.java:875)
	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
	at com.google.common.util.concurrent.Futures$ImmediateFuture.addListener(Futures.java:104)
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:871)
	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture$1.run(Futures.java:875)
	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
	at com.google.common.util.concurrent.Futures$ImmediateFuture.addListener(Futures.java:104)
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:871)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by doanduyhai** [comment]
Fixed by Achilles 3.2.1
