### ISSUE TITLE
Cannot install achilles 3.2.2 in OSGI environment due to info.archinnov.achilles.json.JacksonMapperFactory missing class from achilles-model

### ISSUE THREAD

**Issue by amorillotraxens** [doanduyhai/Achilles#221]
The package info.archinnov.achilles.json appears in achilles-model and achilles-core. Only achilles-model exports this package. When trying to build the PersistenceManagerFactory, a class not found is raised :

smx@root> Exception in thread "SpringOsgiExtenderThread-26" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'daoDriverCassandraImpl' defined in URL [bundle://273.1:0/META-INF/spring/bundle-context.xml]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: info/archinnov/achilles/json/JacksonMapperFactory
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1514)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:636)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:934)
        at org.springframework.osgi.context.support.AbstractDelegatedExecutionApplicationContext.access$1600(AbstractDelegatedExecutionApplicationContext.java:69)
        at org.springframework.osgi.context.support.AbstractDelegatedExecutionApplicationContext$4.run(AbstractDelegatedExecutionApplicationContext.java:355)
        at org.springframework.osgi.util.internal.PrivilegedUtils.executeWithCustomTCCL(PrivilegedUtils.java:85)
        at org.springframework.osgi.context.support.AbstractDelegatedExecutionApplicationContext.completeRefresh(AbstractDelegatedExecutionApplicationContext.java:320)
        at org.springframework.osgi.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor$CompleteRefreshTask.run(DependencyWaiterApplicationContextExecutor.java:132)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: info/archinnov/achilles/json/JacksonMapperFactory
        at info.archinnov.achilles.persistence.PersistenceManagerFactory.<init>(PersistenceManagerFactory.java:73)
        at info.archinnov.achilles.persistence.PersistenceManagerFactory$PersistenceManagerFactoryBuilder.build(PersistenceManagerFactory.java:744)
        at com.traxens.traxhub.dao.cassandra.impl.DaoDriverCassandraImpl.start(DaoDriverCassandraImpl.java:67)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1640)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1581)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1511)
        ... 14 more
Caused by: java.lang.ClassNotFoundException: info.archinnov.achilles.json.JacksonMapperFactory not found by info.archinnov.achilles-model [268]
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1556)
        at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1993)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.apache.felix.framework.BundleWiringImpl.getClassByDelegation(BundleWiringImpl.java:1397)
        at org.apache.felix.framework.BundleWiringImpl.searchImports(BundleWiringImpl.java:1577)
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1507)
        at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:77)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1993)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 24 more

**Comment by doanduyhai** [comment]
Same issue as previously with package scoping. I'll rename the package in the **achilles-core** module

**Comment by doanduyhai** [comment]
Achilles 3.2.3 has been released. It will be available tomorrow on Maven Central
