### ISSUE TITLE
ByteBuffer as type for entity element cause nullpointer in achilles

### ISSUE THREAD

**Issue by n0rad** [doanduyhai/Achilles#234]
Caused by: java.lang.NullPointerException: null
	at info.archinnov.achilles.internals.schema.SchemaValidator.lambda$validateColumns$86(SchemaValidator.java:62)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at info.archinnov.achilles.internals.schema.SchemaValidator.validateColumns(SchemaValidator.java:60)
	at info.archinnov.achilles.internals.metamodel.AbstractEntityProperty.validateSchema(AbstractEntityProperty.java:333)
	at info.archinnov.achilles.internals.runtime.AbstractManagerFactory.lambda$validateSchema$389(AbstractManagerFactory.java:127)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at info.archinnov.achilles.internals.runtime.AbstractManagerFactory.validateSchema(AbstractManagerFactory.java:127)
	at info.archinnov.achilles.internals.runtime.AbstractManagerFactory.bootstrap(AbstractManagerFactory.java:104)
	at info.archinnov.achilles.generated.ManagerFactory.<init>(ManagerFactory.java:25)
	at info.archinnov.achilles.generated.ManagerFactoryBuilder.build(ManagerFactoryBuilder.java:38)

**Comment by doanduyhai** [comment]
I have setup an integration test using `ByteBuffer` and it works for me:

### Entity definition
```java
@Entity(table = EntityWithByteBufferType.TABLE)
public class EntityWithByteBufferType {

    public static final String TABLE = "table_with_bytebuffer";

    @PartitionKey
    private Long id;

    @Column
    private ByteBuffer value;

    public EntityWithByteBufferType() {
    }

    public EntityWithByteBufferType(Long id, ByteBuffer value) {
        this.id = id;
        this.value = value;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public ByteBuffer getValue() {
        return value;
    }

    public void setValue(ByteBuffer value) {
        this.value = value;
    }
}
```
### Test
```java
    @Test
    public void should_support_bytebuffer_type() throws Exception {
        //Given
        final Cluster cluster = CassandraEmbeddedServerBuilder
                .builder()
                .buildNativeCluster();

        final Long id = RandomUtils.nextLong(0, Long.MAX_VALUE);
        final ByteBuffer value = ByteBuffer.wrap(new byte[]{id.byteValue()});

        //When
        final ManagerFactory managerFactory = ManagerFactoryBuilder
                .builder(cluster)
                .withManagedEntityClasses(EntityWithByteBufferType.class)
                .doForceSchemaCreation(true)
                .withDefaultKeyspaceName(DEFAULT_CASSANDRA_EMBEDDED_KEYSPACE_NAME)
                .build();

        final EntityWithByteBufferType_Manager manager = managerFactory
                .forEntityWithByteBufferType();

        final EntityWithByteBufferType entity = new EntityWithByteBufferType(id, value);

        manager.crud().insert(entity).execute();

        final Row one = manager.getNativeSession().execute("SELECT * FROM " + EntityWithByteBufferType.TABLE +
                " WHERE id = " + id).one();

        assertThat(one).isNotNull();
        assertThat(one.getBytes("value")).isEqualTo(value);
    }
```

**Comment by n0rad** [comment]
hum, it was mapped on a blob, don't know if achilles create a blob for it in your test

**Comment by doanduyhai** [comment]
Logs of the integration test

<pre>
14:04:50.244 [main] INFO  i.a.a.embedded.AchillesInitializer - Creating keyspace : CREATE keyspace IF NOT EXISTS achilles_embedded WITH REPLICATION = {'class':'SimpleStrategy', 'replication_factor':1} AND DURABLE_WRITES=false
14:04:51.770 [main] DEBUG ACHILLES_DDL_SCRIPT - 
CREATE TABLE IF NOT EXISTS achilles_embedded.table_with_bytebuffer(
		id bigint,
		value blob,
		PRIMARY KEY(id));
14:04:53.015 [main] DEBUG ACHILLES_DML_STATEMENT - Query ID 13d1fe77-0878-4b47-b668-e9cba35cfc97 : [INSERT INTO achilles_embedded.table_with_bytebuffer (id,value) VALUES (:id,:value) USING TTL :ttl;] with CONSISTENCY LEVEL [LOCAL_ONE]
14:04:53.016 [main] DEBUG ACHILLES_DML_STATEMENT - 	 Java bound values : [3660369682249627648, 0xc6cef4a60cf48f32fabccfb0c858032b... (100), 0]
14:04:53.016 [main] DEBUG ACHILLES_DML_STATEMENT - 	 Encoded bound values : [3660369682249627648, 0xc6cef4a60cf48f32fabccfb0c858032b... (100), 0]
14:04:53.040 [achilles-default-executor-1] DEBUG ACHILLES_DML_STATEMENT - ResultSet[ exhausted: true, Columns[]]
14:04:53.040 [achilles-default-executor-1] DEBUG ACHILLES_DML_STATEMENT - Query ID 13d1fe77-0878-4b47-b668-e9cba35cfc97 results : 


</pre>

**Comment by n0rad** [comment]
Then, rhis was probably not the root cause :/ sorry
