### ISSUE TITLE
Exception when log level is set to debug

### ISSUE THREAD

**Issue by bhuvanrawal** [doanduyhai/Achilles#249]
Exception when starting up the application in schema validator.
info.archinnov.achilles.internals.schema.SchemaValidator.java:89

SchemaValidator.java:89:

if (LOGGER.isDebugEnabled()) {
LOGGER.debug(format("Validating index on column % of table %s",
cqlColumn, indexMetadata.getTable().getName()));
}
Please find the Stacktrace below:
    Caused by: java.util.IllegalFormatConversionException: o != java.lang.String
       at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4302)
       at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2793)
       at java.util.Formatter$FormatSpecifier.print(Formatter.java:2747)
       at java.util.Formatter.format(Formatter.java:2520)
       at java.util.Formatter.format(Formatter.java:2455)
       at java.lang.String.format(String.java:2928)
       at info.archinnov.achilles.internals.schema.SchemaValidator.validateIndex(SchemaValidator.java:89)
       at info.archinnov.achilles.internals.schema.SchemaValidator.validateColumns(SchemaValidator.java:75)
       at info.archinnov.achilles.internals.metamodel.AbstractEntityProperty.validateSchema(AbstractEntityProperty.java:336)
       at info.archinnov.achilles.internals.runtime.AbstractManagerFactory.lambda$validateSchema$371(AbstractManagerFactory.java:151)
       at info.archinnov.achilles.internals.runtime.AbstractManagerFactory$$Lambda$695/1865844141.accept(Unknown Source)
       at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
       at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
       at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
       at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
       at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
       at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
       at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
       at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
       at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
       at info.archinnov.achilles.internals.runtime.AbstractManagerFactory.validateSchema(AbstractManagerFactory.java:151)
       at info.archinnov.achilles.internals.runtime.AbstractManagerFactory.bootstrap(AbstractManagerFactory.java:114)
       at info.archinnov.achilles.generated.ManagerFactory.<init>(ManagerFactory.java:88)

**Comment by doanduyhai** [comment]
Fixed by PR #250
