### ISSUE TITLE
Workspace error when 4.1.0 is added to the pom

### ISSUE THREAD

**Issue by suyambuganesh** [doanduyhai/Achilles#251]
Machine properties:

> eclipse.buildId=3.7.3.201602250940-RELEASE-e45 (Spring Tool Suite)
java.version=1.8.0_71
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US

Stack trace:

> !ENTRY org.eclipse.core.resources 4 2 2016-04-10 21:31:00.157
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.NoClassDefFoundError: com/sun/tools/javac/code/Symbol$ClassSymbol
	at info.archinnov.achilles.internals.apt.AptUtils.isJavaCompiler(AptUtils.java:315)
	at info.archinnov.achilles.internals.parser.AnnotationTree.findOptionalViewBaseClass(AnnotationTree.java:599)
	at info.archinnov.achilles.internals.codegen.meta.EntityMetaCodeGen.buildEntityMeta(EntityMetaCodeGen.java:73)
	at info.archinnov.achilles.internals.parser.EntityParser.parseEntity(EntityParser.java:44)
	at info.archinnov.achilles.internals.apt.processors.meta.AchillesProcessor.lambda$process$283(AchillesProcessor.java:102)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)

**Comment by suyambuganesh** [comment]
apparently tools.jar is not added to classpath in eclipse, which is required for code generation. Code generation worked fine once tools.jar was added to classpath. This hack is not required for Intellij Idea, it works without any issues.
