### ISSUE TITLE
Getting an Run time Error

### ISSUE THREAD

**Issue by harjitdotsingh** [doanduyhai/Achilles#256]
I'm using this code
 final SimpleStatement statement = new SimpleStatement("SELECT * FROM livesearchhistory WHERE queryid = :qid");

        LiveSearchHistory fetchedResults = recommManager.query().typedQueryForSelect(statement,"queryID").getOne();

and Getting a error 

java.util.MissingFormatArgumentException: Format specifier '%s'

	at java.util.Formatter.format(Formatter.java:2519)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at info.archinnov.achilles.internals.query.typed.TypedQueryValidator.validateCorrectTableName(TypedQueryValidator.java:35)
	at info.archinnov.achilles.internals.query.typed.TypedQuery.<init>(TypedQuery.java:70)
	at info.archinnov.achilles.internals.runtime.AbstractManager.typedQueryForSelectInternal(AbstractManager.java:160)

After looking at the code I see the code in TypeQueryValidator is incorrect. You have two %s but only one String.

**Comment by doanduyhai** [comment]
Thanks for the feedback, what is your Achilles version ?

**Comment by harjitdotsingh** [comment]
4.2.1

**Comment by doanduyhai** [comment]
Ok, I found the bug, it's not critical since the code path is activated only when DEBUG log level is enabled, will be fixed in the next release for sure
