### ISSUE TITLE
Incorrect bound values for UPDATE when using TTL

### ISSUE THREAD

**Issue by mfix** [doanduyhai/Achilles#259]
Hi,

I want to update TTL of a row with such a code:
`messageByUserLatestEntityManager.dsl()
                    .update().fromBaseTable().userIsSender_Set(messageByUserLatestEntity.getUserIsSender())
                    .where()
                        .userId_Eq(messageByUserLatestEntity.getUserId())
                        .bucket_Eq(messageByUserLatestEntity.getBucket())
                        .threadId_Eq(messageByUserLatestEntity.getThreadId())
                        .messageId_Eq(messageByUserLatestEntity.getMessageId())
                    .usingTimeToLive(this.getTtl(threadEntity.getTripDate(), new Date(unixTimestamp(threadEntity.getCreatedAt()))))
                    .executeAsync()`

but I receive following error:

> Codec not found for requested operation: [bigint <-> java.lang.Boolean]

java.lang.Boolean changes each time I change the updated field (accordingly to it's type).
Without `.usingTimeToLive` line all works just fine.

Checked on Achilles 4.1.0 and also 4.2.2

**Comment by doanduyhai** [comment]
Can you please give the full stack trace ?

**Comment by doanduyhai** [comment]
```
Caused by: com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [bigint <-> java.lang.Boolean]
at com.datastax.driver.core.CodecRegistry.notFound(CodecRegistry.java:679)
at com.datastax.driver.core.CodecRegistry.createCodec(CodecRegistry.java:540)
at com.datastax.driver.core.CodecRegistry.findCodec(CodecRegistry.java:520)
at com.datastax.driver.core.CodecRegistry.codecFor(CodecRegistry.java:470)
at com.datastax.driver.core.AbstractGettableByIndexData.codecFor(AbstractGettableByIndexData.java:77)
at com.datastax.driver.core.BoundStatement.bind(BoundStatement.java:196)
at com.datastax.driver.core.DefaultPreparedStatement.bind(DefaultPreparedStatement.java:126)
at info.archinnov.achilles.internals.statements.BoundStatementWrapper.<init>(BoundStatementWrapper.java:50)
at info.archinnov.achilles.internals.query.dsl.update.AbstractUpdateEnd.getInternalBoundStatementWrapper(AbstractUpdateEnd.java:150)
at info.archinnov.achilles.internals.query.dsl.update.AbstractUpdateEnd.executeAsyncWithStats(AbstractUpdateEnd.java:99)
at info.archinnov.achilles.internals.query.action.MutationAction.executeAsync(MutationAction.java:60)
at com.blablacar.api.messaging.command.service.DenormalizationService.updateTripDate(DenormalizationService.java:678)
at com.blablacar.api.messaging.command.service.CommandService.updateTripDate(CommandService.java:273)
... 59 common frames omitted
```

**Comment by doanduyhai** [comment]
Ok, the reason is that encoded bound values are set with incorrect order

```sql
UPDATE messaging_query.latest_messages_by_user USING TIMESTAMP :ttl SET user_is_sender=:user_is_sender WHERE user_id=:userId_Eq AND bucket=:bucket_Eq AND thread_id=:threadId_Eq AND message_id=:messageId_Eq;
```

Bound values:

```
0 = {Boolean@10700} "true"
1 = {HeapByteBuffer@10794} "java.nio.HeapByteBuffer[pos=0 lim=3 cap=3]"
2 = "2016,2"
3 = {UUID@10796} "cefc16f0-69ea-11e6-851c-00004131b5d2"
4 = {UUID@10797} "cefc6510-69ea-11e6-8dd1-00003f0e7524"
5 = {Integer@10798} "564808"
```

**Comment by mfix** [comment]
Thanks for investigating. I guess I cannot do anything myself about it - any idea when you can resolve this?

**Comment by doanduyhai** [comment]
The fix is committed, I'll try a release soon
