### ISSUE TITLE
Update to map generates invalid WHERE clause and repeated map value entry setting in 5.1.3

### ISSUE THREAD

**Issue by andrewv99** [doanduyhai/Achilles#274]
Hi,

I am getting a problem in 5.1.3 / Datastax driver 3.1.1 / Cassandra 3.4, where updates to map entries attempt to trigger the generation of a prepared statement with a repeated WHERE clause equality constraint and a repeated data set action (if the map data is a UDT, but not if it is a simple type).

Details:

@Table
public class MyTable
{
	@PartitionKey(value = 1)
	@TimeUUID
	private UUID id;

	@Column(value = "am")
	@EmptyCollectionIfNull
	private Map<@Enumerated AggregateType, String> aggregateDataMap;

	@Column(value = "apm")
	@EmptyCollectionIfNull
	private Map<String, @Frozen MyUDT> keyToMyUDTMap;

...
}

Case #1:

BoundStatement update = fromBaseTable
	.aggregateDataMap()
	.PutTo(aggregateType,
		valueStr)
	.where().id().Eq(id)
	.generateAndGetBoundStatement();

DEBUG output just before the exception:

2016-11-12 09:56:44,782 DEBUG [info.archinnov.achilles.internals.cache.StatementsCache] (default task-12) Preparing dynamic query : UPDATE spitfire.person_pro
file SET apm=apm+:apm,am[:aggregateDataMap_key]=:aggregateDataMap_value WHERE id=:id AND id=:id;

Note: the map entry set is not repeated if the data type is a simple one.

Relevant stack back-trace:

Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.datastax.driver.core.exceptions.InvalidQueryException: id cannot be restricted by more than one relation if it includes an Equal
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203) [guava.jar:]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937) [guava.jar:]
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739) [guava.jar:]
        at info.archinnov.achilles.internals.cache.StatementsCache.getDynamicCache(StatementsCache.java:72) [achilles-core.jar:]
        at info.archinnov.achilles.internals.runtime.RuntimeEngine.prepareDynamicQuery(RuntimeEngine.java:102) [achilles-core.jar:]
        at info.archinnov.achilles.internals.runtime.RuntimeEngine.prepareDynamicQuery(RuntimeEngine.java:95) [achilles-core.jar:]
        at info.archinnov.achilles.internals.dsl.query.update.AbstractUpdateEnd.getInternalBoundStatementWrapper(AbstractUpdateEnd.java:147) [achilles-core.jar:]
        at info.archinnov.achilles.internals.dsl.query.update.AbstractUpdateEnd.generateAndGetBoundStatement(AbstractUpdateEnd.java:120) [achilles-core.jar:]

Case #2:

Identical stack back-trace to the one above.

final BoundStatement update = fromBaseTable
		.keyToMyUDTMap()
		.PutTo(key,
		myUDTData)
		.where().id().Eq(id)
		.generateAndGetBoundStatement();

2016-11-12 10:34:37,292 DEBUG [info.archinnov.achilles.internals.runtime.RuntimeEngine] (default task-25) Preparing dynamic query UPDATE spitfire.person_profile SET apm[:keyToMyUDTMap_key]=:keyToMyUDTMap_value,apm[:keyToMyUDTMap_key]=:keyToMyUDTMap_value WHERE id=:id AND id=:id;

So in this second case, the WHERE clause constraint is repeated, and the map entry setting is also repeated.

Is this a bug, or could it be that I need to specify some configuration or option to correct this error ?

Note, if I set all map data in one go, it works (but is less efficient):

BoundStatement update = fromBaseTable
	.keyToMyUDTMap()
	.AddAllTo(keyToMyUDTMap)
	.where().id().Eq(id)
	.generateAndGetBoundStatement();

Thanks
Andrew

**Comment by andrewv99** [comment]
I have just tried again with 5.1.4, but I get the same error.

**Comment by doanduyhai** [comment]
I'll try to reproduce your issue this weekend.

**Comment by doanduyhai** [comment]
I couldn't reproduce your issue, I created your entity, let Achilles generates all the DSL classes.

My unit test is running fine:

```java
    @Test
    public void should_generate_query_for_map_update() throws Exception {
        //Given
        final UUID id = UUIDs.timeBased();

        //When
        final BoundStatement bs = manager
                .dsl()
                .update()
                .fromBaseTable()
                .aggregateDataMap().PutTo(AggregateType.LOCAL, "LOCAL")
                .where()
                .id().Eq(id)
                .generateAndGetBoundStatement();

        //Then
        assertThat(bs.preparedStatement().getQueryString())
            .isEqualTo("UPDATE achilles_embedded.mytable SET am[:aggregateDataMap_key]=:aggregateDataMap_value WHERE id=:id;");
    }
```

What I suspect is that your did a 

```java
MyTable_Update.MyTable_UpdateFrom fromBaseTable  = manager
                .dsl()
                .update()
                .fromBaseTable();

```

and then you **re-use** the **same** instance of `fromBaseTable` for multiple requests, which is **bad** because the DSL intermediary classes are **stateful** and should not be shared between different queries

**Comment by andrewv99** [comment]
Hi,

What you suspected is what I did. I had tried to factor the fromBaseTable  part out because I thought it would improve efficiency, not knowing of any stateful side effect if reused. To avoid anyone else having the same issue, would it be possible to add a check for the stateful objects (the ones for this case any any others in your library), so that they throw an IllegalStateException("") (or similar) if incorrectly reused a second time ?

Many thanks for your very quick and helpful follow ups : )
Andrew

**Comment by doanduyhai** [comment]
I guess adding a warning message in the documentation is easier than trying to enforce the non-reuse of DSL classes. There is no easy way to check that a DSL class is being re-used for different queries
