### ISSUE TITLE
achilles-junit(embedded cassandra) raises 2 exceptions during junit tests run

### ISSUE THREAD

**Issue by vrudikov** [doanduyhai/Achilles#279]
Finished test are marked with green. So tests are ok.

The first one is related to Sigar native library:
```
15:16:30.036 [pool-1-thread-1] INFO org.apache.cassandra.utils.SigarLibrary - Initializing SIGAR library
15:16:30.182 [pool-1-thread-1] DEBUG Sigar - no sigar-amd64-winnt.dll in java.library.path
org.hyperic.sigar.SigarException: no sigar-amd64-winnt.dll in java.library.path
	at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:172)
	at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:100)
	at org.apache.cassandra.utils.SigarLibrary.<init>(SigarLibrary.java:47)
	at org.apache.cassandra.utils.SigarLibrary.<clinit>(SigarLibrary.java:28)
	at org.apache.cassandra.service.StartupChecks$7.execute(StartupChecks.java:216)
	at org.apache.cassandra.service.StartupChecks.verify(StartupChecks.java:112)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:187)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:585)
	at info.archinnov.achilles.embedded.ServerStarter.lambda$start$0(ServerStarter.java:164)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Solution:
I downloaded binary libs from here [hyperic-sigar-1.6.4.zip](https://sourceforge.net/projects/sigar/files/sigar/1.6/hyperic-sigar-1.6.4.zip/download).
Unpacked it to "root/sigar" folder and added system property initialization to the test to avoid this error

```
@BeforeClass
public static void init() {
    System.setProperty("org.hyperic.sigar.path", "C://sigar");
}
```

Anyway, this is not good. Another way is to try to include this library - [sigar-native-deps](https://mvnrepository.com/artifact/sigar/sigar-native-deps/1.6.4) but i can't get rid of the exception above. I think some configuration steps needed

The second one is related to datastax core:
```
14:12:13.977 [main] DEBUG com.datastax.driver.core.Native - Could not load JNR C Library, native system calls through this library will not be available
java.lang.UnsatisfiedLinkError: unknown
	at jnr.ffi.provider.jffi.NativeLibrary.loadNativeLibraries(NativeLibrary.java:87)
	at jnr.ffi.provider.jffi.NativeLibrary.getNativeLibraries(NativeLibrary.java:70)
	at jnr.ffi.provider.jffi.NativeLibrary.getSymbolAddress(NativeLibrary.java:49)
	at jnr.ffi.provider.jffi.NativeLibrary.findSymbolAddress(NativeLibrary.java:59)
	at jnr.ffi.provider.jffi.AsmLibraryLoader.generateInterfaceImpl(AsmLibraryLoader.java:117)
	at jnr.ffi.provider.jffi.AsmLibraryLoader.loadLibrary(AsmLibraryLoader.java:59)
	at jnr.ffi.provider.jffi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:43)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:290)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:269)
	at com.datastax.driver.core.Native$LibCLoader.<clinit>(Native.java:108)
	at com.datastax.driver.core.Native.isGettimeofdayAvailable(Native.java:190)
	at com.datastax.driver.core.ClockFactory.newInstance(Clock.java:51)
	at com.datastax.driver.core.AbstractMonotonicTimestampGenerator.<init>(AbstractMonotonicTimestampGenerator.java:43)
	at com.datastax.driver.core.LoggingMonotonicTimestampGenerator.<init>(LoggingMonotonicTimestampGenerator.java:49)
	at com.datastax.driver.core.AtomicMonotonicTimestampGenerator.<init>(AtomicMonotonicTimestampGenerator.java:50)
	at com.datastax.driver.core.AtomicMonotonicTimestampGenerator.<init>(AtomicMonotonicTimestampGenerator.java:37)
	at com.datastax.driver.core.policies.Policies.defaultTimestampGenerator(Policies.java:122)
	at com.datastax.driver.core.policies.Policies$Builder.build(Policies.java:287)
	at com.datastax.driver.core.Cluster$Builder.getConfiguration(Cluster.java:1263)
	at com.datastax.driver.core.Cluster.<init>(Cluster.java:118)
	at com.datastax.driver.core.Cluster.buildFrom(Cluster.java:183)
	at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:1281)
	at info.archinnov.achilles.embedded.AchillesInitializer.createCluster(AchillesInitializer.java:117)
	at info.archinnov.achilles.embedded.AchillesInitializer.initializeCluster(AchillesInitializer.java:98)
	at info.archinnov.achilles.embedded.AchillesInitializer.initializeFromParameters(AchillesInitializer.java:58)
	at info.archinnov.achilles.embedded.CassandraEmbeddedServer.<init>(CassandraEmbeddedServer.java:64)
	at info.archinnov.achilles.embedded.CassandraEmbeddedServerBuilder.buildServer(CassandraEmbeddedServerBuilder.java:523)
	at info.archinnov.achilles.junit.AchillesTestResource.buildServer(AchillesTestResource.java:141)
	at info.archinnov.achilles.junit.AchillesTestResource.<init>(AchillesTestResource.java:118)
	at info.archinnov.achilles.junit.AchillesTestResourceBuilder.build(AchillesTestResourceBuilder.java:216)
```

But I found details on official [Datastax Driver](https://docs.datastax.com/en/developer/java-driver/3.1/faq/osgi/) page. How about to mention that in Wiki?

**Comment by kadamvandita** [comment]
Any solution to this?

**Comment by vrudikov** [comment]
1. Sigar - no sigar-amd64-winnt.dll in java.library.path - stays the same
2. Could not load JNR C Library, native system calls through this library will not be available
Strange but i don't receive such message since that time

**Comment by ranjankumar03** [comment]
Any workaround of the mentioned issue.?

atastax.driver.core.Native:113 - Could not load JNR C Library, native system calls through this library will not be available
java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider
        at jnr.ffi.provider.InvalidProvider$1.loadLibrary(InvalidProvider.java:48)
        at jnr.ffi.LibraryLoader.load(LibraryLoader.java:290)
        at jnr.ffi.LibraryLoader.load(LibraryLoader.java:269)
        at com.datastax.driver.core.Native$LibCLoader.<clinit>(Native.java:108)
        at com.datastax.driver.core.Native.isGettimeofdayAvailable(Native.java:190)
        at com.datastax.driver.core.ClockFactory.newInstance(Clock.java:51)
        at com.datastax.driver.core.AbstractMonotonicTimestampGenerator.<init>(AbstractMonotonicTimestampGenerator.java:43)
        at com.datastax.driver.core.LoggingMonotonicTimestampGenerator.<init>(LoggingMonotonicTimestampGenerator.java:49)
        at com.datastax.driver.core.AtomicMonotonicTimestampGenerator.<init>(AtomicMonotonicTimestampGenerator.java:50)
        at com.datastax.driver.core.AtomicMonotonicTimestampGenerator.<init>(AtomicMonotonicTimestampGenerator.java:37)
        at com.datastax.driver.core.policies.Policies.defaultTimestampGenerator(Policies.java:121)
        at com.datastax.driver.core.policies.Policies$Builder.build(Policies.java:286)
        at com.datastax.driver.core.Cluster$Builder.getConfiguration(Cluster.java:1317)
        at com.datastax.driver.core.Cluster.<init>(Cluster.java:113)
        at com.datastax.driver.core.Cluster.buildFrom(Cluster.java:178)
        at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:1335)

**Comment by kadamvandita** [comment]
Need to increase wait time for Cassandra server in Achilles source code

**Comment by ranjankumar03** [comment]
Where to increase this wait time? @kadamvandita

**Comment by jgmatos** [comment]
I have this problem for a long time now. Is this ever going to get solved?

**Comment by jgmatos** [comment]
@ranjankumar03   I finally figured out a workaround (not a solution for the root cause, but a way to stop the exception from appearing in the logs): I answered it in [here](https://stackoverflow.com/a/46039091/4828060)

**Comment by doanduyhai** [comment]
The Sigar-related exception does not prevent **Achilles** embedded to start correctly...

**Comment by jgmatos** [comment]
@doanduyhai In my case Achilles works just fine, as I am able to perform my tests resorting to its mock services. Still, I was getting that exception in my logs.

**Comment by RaAleks** [comment]
Hi, i have the same exception UnsatisfiedLinkError, any solution?

**Comment by doanduyhai** [comment]
Guys, I think your issue is related to the Datastax java driver, some more info here: https://groups.google.com/a/lists.datastax.com/forum/#!topic/java-driver-user/ONpgXJyqTu0
