### ISSUE TITLE
achillis exception

### ISSUE THREAD

**Issue by Nikitakhanna92** [doanduyhai/Achilles#281]
info.archinnov.achilles.exception.AchillesException: Varargs for field 'affiliateId' should not be null/empty
	at info.archinnov.achilles.validation.Validator.validateTrue(Validator.java:119)
	at info.archinnov.achilles.generated.dsl.Affiliate_Select$Affiliate_SelectWhere_AffiliateId$Relation.IN(Affiliate_Select.java:892)
	at com.prontoitlabs.mobiadz.repository.AffiliateRepository.getAffiliates(AffiliateRepository.java:115)
	at com.prontoitlabs.mobiadz.service.impl.OfferServiceImpl.getAffiliateNameAndIds(OfferServiceImpl.java:778)
	at com.prontoitlabs.mobiadz.service.impl.OfferServiceImpl.setResponseIfApprovalNotRequired(OfferServiceImpl.java:756)
	at com.prontoitlabs.mobiadz.service.impl.OfferServiceImpl.getAffiliateList(OfferServiceImpl.java:677)
	at com.prontoitlabs.mobiadz.controller.OfferController.affiliatesByOfferId(OfferController.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)

**Comment by doanduyhai** [comment]
Well it's pretty clear isn't it ?

* Varargs for field 'affiliateId' should not be null/empty*

`at info.archinnov.achilles.generated.dsl.Affiliate_Select$Affiliate_SelectWhere_AffiliateId$Relation.IN`

You're using the `IN` clause so you need to provide multiple values as varargs ...
