### ISSUE TITLE
Achilles ignores RegularStatement prebound values in native queries

### ISSUE THREAD

**Issue by kevinmic** [doanduyhai/Achilles#296]
Take the following query

select * from MyTable where pkey = '1';

If I try and represent this in a RegularStatement I would do the following.
```
RegularStatement statement = QueryBuilder.select().from("ks","table").where(QueryBuilder.eq("pkey", "1"));
```

Now passing this into achilles
```
MyTable_Manager.manager.raw().nativeQuery(statement);
```

This will result in the error -- "InvalidQueryException: Invalid unset value for column pkey".
Instead achilles is forcing me to pass in the values of the binding like so.
```
MyTable_Manager.manager.raw().nativeQuery(statement, 'pkey');
```

I can do this instead and it works.
```
MyTable_Manager.getNativeSession().execute(statement);
```

Why does achilles force me to rebind my values?

**Comment by doanduyhai** [comment]
I'm running an integration test similar to your scenario and it works ...

![image](https://cloud.githubusercontent.com/assets/1532977/23771208/6ae7476c-0516-11e7-943a-ff6ff76d304d.png)


Can you provide a full stack-trace of your exception ?

**Comment by kevinmic** [comment]
[https://github.com/kevinmic/achilles-bug](https://github.com/kevinmic/achilles-bug)

In that git repository I demonstrate the issue I am having.

MyTableDao.findPartitionId uses DSL and works

MyTableDao.findByPartitionId_wQueryBuilder_and_boundValues  works fine but I have to bind the values twice

MyTableDao.findByPartitionId_wQueryBuilder throws the following exception


```
com.datastax.driver.core.exceptions.InvalidQueryException: Invalid unset value for column mykey

	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
	at info.archinnov.achilles.internals.dsl.AsyncAware.extractCauseFromExecutionException(AsyncAware.java:34)
	at info.archinnov.achilles.internals.dsl.action.SelectAction.getList(SelectAction.java:100)
	at com.checkbug.MyTableDao.findByPartitionId_wQueryBuilder(MyTableDao.java:44)
	at com.checkbug.MyTableDaoTest.test_nativeQuery_boundValues_problem(MyTableDaoTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Invalid unset value for column mykey
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:136)
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:179)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:177)
	at com.datastax.driver.core.RequestHandler.access$2500(RequestHandler.java:46)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:797)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:631)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1070)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:993)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1280)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:890)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:564)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:505)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:419)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by kevinmic** [comment]
While I demonstrated this problem using .raw().typedQueryForSelect my real issue is during partial key deletes where the dsl() language does not support partial key deletes.    So I have this problem using either .raw().typedQueryForSelect or using .raw().nativeQuery()


See issue [https://github.com/doanduyhai/Achilles/issues/295](https://github.com/doanduyhai/Achilles/issues/295)

**Comment by doanduyhai** [comment]
OK let me check your example

**Comment by doanduyhai** [comment]
Ok I've found the issue, it's not really an **Achilles** bug but it is due to how the Java driver generates the query string for `RegularStatement`

```java

RegularStatement withString = QueryBuilder.select().from(MyTable.TABLE_NAME)
    .where(QueryBuilder.eq("myKey", "12"));
RegularStatement withInt = QueryBuilder.select().from(MyTable.TABLE_NAME)
    .where(QueryBuilder.eq("myKey", 12));

System.out.println("**** WithString : " + withString.getQueryString());
System.out.println("**** withInt : " + withInt.getQueryString());
```

Output 

```
**** WithString : SELECT * FROM mytable WHERE myKey=?;
**** withInt : SELECT * FROM mytable WHERE myKey=12;
```

Indeed, the Java driver put into the query string if your query params are numeric values, otherwise it's a bindMarker (`?`)

So **Achilles** API forces you to always provide query params even for RegularStatements:

![image](https://cloud.githubusercontent.com/assets/1532977/24083639/0c3a8db0-0cdb-11e7-8dcf-54c65d981b51.png)

**Comment by kevinmic** [comment]
I don't understand why this isn't a bug.    The java driver is producing the correct query string that will protect from SQL Injection attacks.   The RegularStatement has the values bound and achilles is losing them.  

If I send the RegularStatement directly to the native session I don't have to rebind the values.   Why should I have to do it if I use Achilles?

**Comment by doanduyhai** [comment]
You don't understand the real problem


![image](https://cloud.githubusercontent.com/assets/1532977/24222896/1061557e-0f54-11e7-8b5e-a9215adccd16.png)


Test results:

```
******** numeric query string : SELECT * FROM test.test WHERE id=10;
******** string query string : SELECT * FROM test.test WHERE id=?;
java.lang.AssertionError: [numeric regular statement does not have values] 
Expecting actual not to be null
```

When creating a RegularStatement with QueryBuilder and injecting a *numeric* value, the value is written directly in the query string so when **Achilles** calls `regularStatement.getValues(protocolVersion, codecRegistry)` the returned byte-buffer is empty !!!

And because of this particular case, **Achilles** has to force you to provide the values injected into your regular statement.

If you are not happy with this behavior, please open a JIRA on the driver-side because the behavior inconsistency comes from the driver

**Comment by kevinmic** [comment]
I don't understand why you need to call "getQueryString" in the first place?   RegularStatement already has all the values bound and can be passed directly to the datastax driver as is, what is the advantage of getting the query string from the statement and rebinding all the values?

**Comment by doanduyhai** [comment]
> what is the advantage of getting the query string from the statement and rebinding all the values?

For DML logger ...

**Comment by doanduyhai** [comment]
Can I close this issue @kevinmic or do you have something else to add ?
