### ISSUE TITLE
cdc_raw_directory required for embedded cassandra

### ISSUE THREAD

**Issue by OldFatCactus** [doanduyhai/Achilles#304]
getting this error when using embedded cassandra:
`Exception (org.apache.cassandra.exceptions.ConfigurationException) encountered during startup: cdc_raw_directory is missing and -Dcassandra.storagedir is not set`

**Comment by doanduyhai** [comment]
Which version of Achilles are you using ?

Can you give me the full stack trace ?

**Comment by OldFatCactus** [comment]
5.2.1

I can't replicate the issue at the moment but I'm actually getting a new error: 
`2017-06-06T20:20:33.225Z : FINE Will try to load mx4j now, if it's in the classpath
2017-06-06T20:20:33.226Z : FINE Will not load MX4J, mx4j-tools.jar is not in the classpath
2017-06-06T20:20:33.353Z : INFO Netty using Java NIO event loop
Exception (java.lang.ExceptionInInitializerError) encountered during startup: null
java.lang.ExceptionInInitializerError
2017-06-06T20:20:33.362Z : SEVERE Exception encountered during startup : null
	at org.apache.cassandra.transport.Server.start(Server.java:130)
	at java.util.Collections$SingletonSet.forEach(Collections.java:4767)
	at org.apache.cassandra.service.NativeTransportService.start(NativeTransportService.java:128)
	at org.apache.cassandra.service.CassandraDaemon.startNativeTransport(CassandraDaemon.java:633)
	at org.apache.cassandra.service.CassandraDaemon.start(CassandraDaemon.java:495)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:600)
	at info.archinnov.achilles.embedded.ServerStarter.lambda$start$0(ServerStarter.java:164)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: name
	at io.netty.util.internal.logging.AbstractInternalLogger.<init>(AbstractInternalLogger.java:39)
	at io.netty.util.internal.logging.Slf4JLogger.<init>(Slf4JLogger.java:30)
	at io.netty.util.internal.logging.Slf4JLoggerFactory.newInstance(Slf4JLoggerFactory.java:67)
	at io.netty.util.internal.logging.InternalLoggerFactory.getInstance(InternalLoggerFactory.java:84)
	at io.netty.util.internal.logging.InternalLoggerFactory.getInstance(InternalLoggerFactory.java:77)
	at io.netty.bootstrap.ServerBootstrap.<clinit>(ServerBootstrap.java:47)
	... 10 more
2017-06-06T20:20:33.363Z : INFO Announcing shutdown`
