### ISSUE TITLE
TestEntityWithStaticAnnotations::should_insert_using_static_strategy_an_consistency_level is flaky

### ISSUE THREAD

**Issue by flakycov** [doanduyhai/Achilles#309]
`TestEntityWithStaticAnnotations::should_insert_using_static_strategy_an_consistency_level` failed for us on commit 5f2a24e but did not fail [on the corresponding run on Travis](https://travis-ci.org/doanduyhai/Achilles/builds/256785518):

```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 11.422 sec <<< FAILURE! - in info.archinnov.achilles.it.TestEntityWithStaticAnnotations
should_insert_using_static_strategy_an_consistency_level(info.archinnov.achilles.it.TestEntityWithStaticAnnotations)  Time elapsed: 0.577 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<"overriden_val"> but was:<null>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at info.archinnov.achilles.it.TestEntityWithStaticAnnotations.should_insert_using_static_strategy_an_consistency_level(TestEntityWithStaticAnnotations.java:90)
```

Our investigation shows that this test is likely flaky. We set up our build environment to be as close to your Travis environment as possible, using Ubuntu 14.04.5 LTS, Java HotSpot 1.8.0_31-b13 and Maven 3.3.9.

**Comment by doanduyhai** [comment]
Interesting, thank you for raising the issue, I'll try to make the test more resilient
