### ISSUE TITLE
Unable to start on new Java version (1.8.0_162-b12)

### ISSUE THREAD

**Issue by robinvandenberg** [doanduyhai/Achilles#331]
This library can't be used with the new jdk/jre version.
It fails to startup.

It is fixed in cassandra 3.11.2 (according to https://issues.apache.org/jira/browse/CASSANDRA-14173)
But this library goes up to 3.11.0

[pool-1-thread-1] ERROR o.a.c.service.CassandraDaemon - Exception encountered during startup
java.lang.AbstractMethodError: org.apache.cassandra.utils.JMXServerUtils$Exporter.exportObject(Ljava/rmi/Remote;ILjava/rmi/server/RMIClientSocketFactory;Ljava/rmi/server/RMIServerSocketFactory;Lsun/misc/ObjectInputFilter;)Ljava/rmi/Remote;
	at javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:150)
	at javax.management.remote.rmi.RMIJRMPServerImpl.export(RMIJRMPServerImpl.java:135)
	at javax.management.remote.rmi.RMIConnectorServer.start(RMIConnectorServer.java:405)
	at org.apache.cassandra.utils.JMXServerUtils.createJMXServer(JMXServerUtils.java:104)
	at org.apache.cassandra.service.CassandraDaemon.maybeInitJmx(CassandraDaemon.java:143)
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:188)
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:600)
	at info.archinnov.achilles.embedded.ServerStarter.lambda$start$0(ServerStarter.java:163)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vrudikov** [comment]
+

**Comment by gmanolache** [comment]
++

**Comment by doanduyhai** [comment]
Ok let me do a release this weekend to upgrade to latest Cassandra version

**Comment by vrudikov** [comment]
Waiting for it... Thank you, @doanduyhai

**Comment by RaAleks** [comment]
++

**Comment by doanduyhai** [comment]
Fixed in Achilles 6.0.0
